FROM frrouting/frr:v8.4.1

# Init router conf CLI
RUN echo 'service integrated-vtysh-config' > /etc/frr/vtysh.conf

# The watchfrr, zebra and staticd daemons are always started.
RUN sed -i \
  -e 's/bgpd=no/bgpd=yes/g' \
  -e 's/ospfd=no/ospfd=yes/g' \
  -e 's/isisd=no/isisd=yes/g' \
  /etc/frr/daemons

COPY ./P2/router.sh .

COPY ./P3/evpn.sh .
COPY ./P3/spine_vtysh.sh .
COPY ./P3/leaf_vtysh.sh .
